[sshd]
enabled = true
action = %(action_)s
         %(action_abuseipdb)s[abuseipdb_apikey="1ff46f49e78d7681df43f14ea971a36a733b9be888a5d3580bd19041b4ddd488c64035a624021f26", abuseipdb_category="18,22"]
destemail = marcus@davage.me
sender = heimdall@heimdall.local
mta = sendmail
protocol = tcp
port = 0:65535
fail2ban_agent = Fail2Ban/%(fail2ban_version)s

